"""empty message

Revision ID: 137b7cbed7f9
Revises: 9781cf247215
Create Date: 2024-04-29 18:00:57.039052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137b7cbed7f9'
down_revision = '9781cf247215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Planet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planet', ['Planet_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Planet_id')

    # ### end Alembic commands ###
