"""empty message

Revision ID: b074763505f7
Revises: 137b7cbed7f9
Create Date: 2024-04-29 18:30:45.533004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b074763505f7'
down_revision = '137b7cbed7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Character_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'character', ['Character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Character_id')

    # ### end Alembic commands ###
