"""empty message

Revision ID: e665a9835d89
Revises: 10f0bd84efe7
Create Date: 2024-04-29 17:02:47.421022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e665a9835d89'
down_revision = '10f0bd84efe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delete_favorite', schema=None) as batch_op:
        batch_op.drop_constraint('delete_favorite_character_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('delete_favorite_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delete_favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('delete_favorite_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key('delete_favorite_character_id_fkey', 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###
